# Generated by Django 4.1.5 on 2023-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_status",
            field=models.CharField(
                choices=[
                    ("NEW", "NEW"),
                    ("CODE_VERIFIED", "CODE_VERIFIED"),
                    ("INFORMATION_FILLED", "INFORMATION_FILLED"),
                    ("DONE", "DONE"),
                ],
                default="NEW",
                max_length=31,
            ),
        ),
    ]
